export * from "./admission.permissions";
export * from "./grade.permissions";
export * from "./report.permissions";
export * from "./student.permissions";
export * from "./payment.permissions";
export * from "./users.permission";
export * from "./record.permissions";
export * from "./dashboard.permissions";
export * from "./roles.permissions"